import  datetime
from    decouple import config # NB remove + config(api) will be replaced with github secrets
import  pandas as pd
from    pandas.tseries.offsets import DateOffset
import  pprint
import  requests
import  sys
from fail import fail_msg

def github_request():
    for x in sys.argv[1:]: # for arguments for secrets
      print(x)
    
    # Make api request with Github credential token
    headers = {'Authorization': 'token ' + config('api')}
    response = requests.get('https://api.github.com/users/Nkosinathi-Bonga-James-Mncube/repos',headers=headers)
    # pprint.pprint(response.json()[0]) # testing purposes
    # print('-----------------------------------------')
    # pprint.pprint(response.json()[1])
    
    # Sort json value from key in API get request
    project_name = [k['full_name'] for k in response.json() if not k['fork'] == True]
    project_created = [k['created_at'] for k in response.json() if not k['fork'] == True]
    project_id = [k['id'] for k in response.json() if not k['fork'] == True]
    project_url = [k['html_url'] for k in response.json() if not k['fork'] == True]
    
    # Create a dictionary from json values 
    data_df = {
                'Project_name':project_name,
                'Created_at':project_created,
                'Id':project_id,
                'html_url':project_url
    }
    # Create dataframe based on dictionary
    df=pd.DataFrame(data_df,columns=['Project_name','Created_at','Id','html_url'])
    df.sort_values(by=['Created_at'],inplace=True,ascending=False)
    df['Created_at']= pd.to_datetime(df['Created_at']) # convert to Date.time.object
    # print(df) # debug
    # x=datetime.datetime.now()+ pd.DateOffset(months=-1) # check previous month (i.e -1)
    x=datetime.date.fromisoformat('2020-04-24')+ pd.DateOffset(months=-1) # debug
    each_repo = df.loc[df['Created_at'].dt.month==x.month].values # find all dates with the previous month in series Created_at
    print(f'------------------------------------------\nLatest project last month in {x.strftime("%b")}-{x.year} \n------------------------------------------')
    print(f'You have a total of {each_repo.shape[0]} new Projects:\n') # return number of total turples with is total number of projects
    for k in each_repo:
      print(f'{k[0]} {k[3]}')
    if each_repo.size == 0:                    
      fail_msg(df)
    print(f'------------------------------------------\nThis report is generated by own project at : https://github.com/Nkosinathi-Bonga-James-Mncube/Linkedin_post_automation\n------------------------------------------')
github_request()