name: LinkedIn post automation
on: push
  #schedule:
  #  - cron: '*/2 * * * *'
jobs:
  build:
    name: Run python script + send email
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Send email
        uses: dawidd6/action-send-mail@v2.4.0
        with:
            server_address : smtp.gmail.com
            server_port: 465
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            subject: Github Action job results
            body: Build job ${{github.repository}} completed successfully
            to: ${{secrets.SEND_TO}}
            from: ${{secrets.SEND_FROM}}
            content_type: text/html
            convert_markdown: true
      - run: |
          python linkedin.py