name: LinkedIn post automation

on: 
  schedule:
    - cron: "0 0 1 * *"
      
jobs:
  LinkedInActions:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo
       uses: actions/checkout@v2
       
     - name: Setup python
       uses: actions/setup-python@v2
       with:
          python-version: 3.8

       
     - name : Run LinkedIn script
       env:
              SEND_TO: ${{secrets.SEND_TO}}
              SEND_FROM: ${{secrets.SEND_FROM}}
              MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
              API: ${{secrets.API}}
              LINKEDIN_ACCESS_TOKEN: ${{secrets.LINKEDIN_ACCESS_TOKEN}}
              LINKEDIN_ID_URN: ${{secrets.LINKEDIN_ID_URN}}
       run: |
          pip install -r requirements.txt
          python src/main.py  $SEND_TO $SEND_FROM $MAIL_PASSWORD $API $LINKEDIN_ACCESS_TOKEN $LINKEDIN_ID_URN